[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PyTaskbar"
dynamic = ["version"]
description = "The ultimate taskbar progress python package!"
readme = "README.md"
authors = [
    {name = "somePythonProgrammer"},
    {name = "Tim Lodemann"}
]
requires-python = ">=3.9"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]
dependencies = []

[dependency-groups]
dev = [
    "mypy",
    "pre-commit",
    "ruff",
]

[project.urls]
Homepage = "https://github.com/timminator/PyTaskbar"
Repository = "https://github.com/timminator/PyTaskbar.git"
Issues = "https://github.com/timminator/PyTaskbar/issues"

[tool.mypy]
strict = true
exclude = ["build"]

[tool.setuptools]
packages = ["PyTaskbar"]

[tool.setuptools.package-data]
fast_ssim = ["py.typed"]

[tool.setuptools.dynamic]
version = {attr = "PyTaskbar.ProgressAPI.__version__"}

[tool.ruff]
exclude = ["build", "venv", ".venv", "__pycache__"]
preview = true
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM", "W"]
ignore = ["E501", "SIM108", "SIM102", "SIM114"]
